# source: https://packaging.python.org/appveyor
cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - TOXENV: "py27"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py27"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py34"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py34"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py35"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py35"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py36"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py36"
      TOX_APPVEYOR_X64: 0
    - TOXENV: "py37"
      TOX_APPVEYOR_X64: 1
    - TOXENV: "py37"
      TOX_APPVEYOR_X64: 0

install:
  - "py -3.6 -m pip install tox tox-appveyor --upgrade"
  - "SET PATH=C:\\Python36-x64\\;C:\\Python36-x64\\Scripts;%PATH%"
  # appveyor cannot into submodules: https://github.com/appveyor/ci/issues/899
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - appveyor DownloadFile http://dist.schmorp.de/libev/libev-4.27.tar.gz
  - tar xzf libev-4.27.tar.gz
  - del libev-4.27.tar.gz
  - cd libev-4.27
#  - choco install make
  - set PATH=C:\msys64\MINGW64\bin;C:\msys64\usr\bin;%PATH%
#  - bash -xlc "set pwd"
#  - bash -xlc "pwd"
  - bash -xlc "cd /c/projects/bjoern/libev-4.27 && ./autogen.sh"
  - bash -xlc "cd /c/projects/bjoern/libev-4.27 && ./configure" # && make && make install"
  - bash -xlc "make -C /c/projects/bjoern/libev-4.27 distcheck"
build: off

test_script:
  - "tox -vv"

artifacts:
  - path: dist\*.whl

on_finish:
  - ps: |
      # upload results to AppVeyor
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unittests.xml))
      $LastExitCode = 0
